- name: install supernode-application-server
  package:
    name: supernode-application-server
    state: latest

- name: copy configuration
  template:
    src: supernode-application-server.toml
    dest: /etc/supernode-application-server/supernode-application-server.toml
    owner: appserver
    group: appserver
    mode: "0640"
  notify:
    - restart supernode-application-server

- name: request letsencrypt certificate
  command: certbot --nginx certonly --non-interactive --agree-tos -m {{ chirpstack_application_server.letsencrypt.email }} -d {{ chirpstack_application_server.fqdn }}
  when: chirpstack_application_server.letsencrypt.request

- name: add nginx proxy
  template:
    src: supernode-application-server.nginx
    dest: /etc/nginx/sites-enabled/supernode-application-server
  notify:
    - reload nginx

- name: start supernode-application-server on boot
  service:
    name: supernode-application-server
    state: started
    enabled: yes
