# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://mxc_as:mxc_as@localhost/mxc_as?sslmode=disable"

[application_server.integration.mqtt]
server="tcp://localhost:1883"
username="mxc_as"
password="mxc_as"

[application_server.external_api]
bind="0.0.0.0:8080"

# It is important to update this secret!
jwt_secret=""
