- name: copy acl configuration
  template:
    src: acls
    dest: /etc/mosquitto/acls
    owner: mosquitto
    group: mosquitto
    mode: 0640
  notify:
    - restart mosquitto

- name: create passwords file
  file:
    path: /etc/mosquitto/passwords
    owner: mosquitto
    group: mosquitto
    mode: 0644
    state: touch

- name: set passwords
  command: mosquitto_passwd -b /etc/mosquitto/passwords {{ item.user }} {{ item.password }}
  no_log: true
  with_items: "{{ mosquitto.users }}"
  notify:
    - restart mosquitto

- name: copy mosquitto configuration
  template:
    src: mosquitto-auth.conf
    dest: /etc/mosquitto/conf.d/mosquitto-auth.conf
    owner: mosquitto
    group: mosquitto
    mode: 0640
  notify:
    - restart mosquitto
