- name: add stretch-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
    default_release: stretch-backports
  with_items:
    - certbot
    - python-certbot-nginx
